### PR TITLE
feat(orientdb-core): add 'edge' option in shortestPath() function to return edge information

### PR DESCRIPTION
**Pull request by blueAnger**
since shortestPath() function didn't return edge information, as I mentioned in #7968 , I made a little change in the OSQLFunctionShortestPath.java to return edge information. 

Example: 

```
select shortestPath(#22:0, #24:0, null, null, {'maxDepth': 10, 'edge': true})
```

### CODE REVIEW

**Comment by luigidellaquila** [comment]
Hi @blueAnger 

Thank you very much, the PR seems OK. 

Just a little change, if you don't mind: I see you added a dependency with `commons-lang3` just to use the `Pair` class; in the codebase we already have two implementations of Pair-like classes, that are `OPair` and `ORawPair`, the latter should be OK for this case, could you please review this PR using that implementation and remove the new dependency?

Thanks

Luigi

**Comment by blueAnger** [comment]
Hi, @luigidellaquila 
Thanks for your notice. Actually I am not quite willing to add a new dependency too, since the ORawPair can do the same thing. I will change it tomorrow morning, for now my network transferring is super slow. -_-|||
Thanks.

**Comment by blueAnger** [comment]
Sorry, I am not quite familiar with github forking workflow....I pull your changes from my local repository, make my own change, and push it to my github forked repository. But somehow my name is in front of your history commits. Is that right? If not, please tell me the right way.
Thanks.

**Comment by luigidellaquila** [comment]
Merged, thank you very much!

Luigi

**Pull request merged**
