### PR TITLE
Fix for #3887

### PR DESCRIPTION
**Pull request by anmoldeep0123**
Regex for a valid class :
"^[_\\p{L}][_\\p{L}\\p{N}]*";

starts with underscore / UNICODE letter  followed by 0 or more (underscore or UNICODE letters or digits) 

if pattern fails to match , throw an exception as code was doing previously

tested for 

ant clean test 
ant clean install

### CODE REVIEW

**Comment by lvca** [comment]
Great, thanks!

**Comment by lvca** [comment]
Maven tests doesn't pass:

    mvn clean test

Reverting it.

**Comment by PhantomYdn** [comment]
Imho it's better to use old approach: it's much faster than regexp.

**Comment by lvca** [comment]
I already included the check for '.' char in last snapshots.

**Pull request merged**
