### PR TITLE
Added a topological scheduler for MATCH execution.

### PR DESCRIPTION
**Pull request by obi1kenobi**
Also included test cases that check for correct behavior for:
- using undefined aliases in $matched evaluations (error is raised)
- queries with circular dependencies (error is raised)
- complex query execution that requires topological sorting (correct results are returned).

I created this against 2.2.x to speed up the development time and allow for release with 2.2.14. If you approve, I can work with you to adapt it to the `develop` branch.

This is a systematic solution to issues like #6931 and #6983.

### CODE REVIEW

**Comment by obi1kenobi** [comment]
@lvca and @luigidellaquila please let me know what you think!

**Comment by luigidellaquila** [comment]
Wow, thank you very much man!
I'm reviewing it now, I hope I'll give you a feedback in a few hours

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

I found a little problem in the algorithm: in a particular situation you reverse the traversal direction

```
 if (!visitedEdges.contains(edge)) {
          // If we are executing in this block, we are in the following situation:
          // - the startNode has not been visited yet;
          // - it has a neighboringNode that has already been visited;
          // - the edge between the startNode and the neighboringNode has not been scheduled yet.
          //
          // The isOutbound value shows us whether the edge is outbound from the point of view of the startNode.
          // However, if there are edges to the startNode, we must visit the startNode from an already-visited
          // neighbor, to preserve the validity of the traversal. Therefore, we negate the value of isOutbound
          // to ensure that the edge is always scheduled in the direction from the already-visited neighbor
          // toward the startNode.
          
          boolean traversalDirection = !isOutbound;
          visitedEdges.add(edge);
          resultingSchedule.add(new EdgeTraversal(edge, traversalDirection));
}

```

In some cases it's not possible, eg. when an edge involves a deep traversal (when it has a WHILE condition or a MAXDEPTH) or when the target node is optional, so you should first check this situation with a

```
edge.item.isBidirectional();
```

Looking at the code, I think that changing the condition is not a solution

```
 if (!visitedEdges.contains(edge) && edge.item.isBidirectional()) {
```

as it will break the whole algorithm. 

Possible solutions here (but no one satisfies me completely):

1. add a `if(!edge.item.isBidirectional()){ continue; }`, but I'm pretty sure that in some situations we will end up with a `throw new OCommandExecutionException("This query contains MATCH conditions that cannot be evaluated")` even if the query could be evaluated following another path

2. abort current evaluation and iterate on another equivalent topological sort, but it complicates the algorithm a bit...

Any thoughts?

Thanks

Luigi

**Comment by obi1kenobi** [comment]
Hi @luigidellaquila, thanks for looking into it.

The direction reversal is not a problem with optional nodes -- in fact, it guarantees that the edge is always considered going *into* the optional node, and not out of it, just the way OrientDB requires it. Please see the test case I included to confirm this.

Would you mind producing a test case for the MAXDEPTH / "while" condition you pointed out will produce an incorrect schedule, so I can use it to debug the problem? The current code satisfies all test cases in the repo, so I don't think that case is covered by the existing code.

Do you think we can merge this in time for 2.2.14? I'd be very happy if that were the case.

**Comment by luigidellaquila** [comment]
Hi @obi1kenobi 

Sure, I'm doing it now. 
2.2.14 should be released tomorrow, with a little luck we can include it ;-)

Thanks

Luigi

**Comment by obi1kenobi** [comment]
Thanks! I'll be AFK in the next three hours to take care of some real-world errands, but I'll look into what you come up with as soon as I get back.

**Comment by luigidellaquila** [comment]
Ok, I have a test case:

```
@Test
  public void testCyclicDeepTraversal() {
    db.command(new OCommandSQL("CREATE CLASS testCyclicDeepTraversalV EXTENDS V")).execute();
    db.command(new OCommandSQL("CREATE CLASS testCyclicDeepTraversalE EXTENDS E")).execute();

    db.command(new OCommandSQL("CREATE VERTEX testCyclicDeepTraversalV SET name = 'a'")).execute();
    db.command(new OCommandSQL("CREATE VERTEX testCyclicDeepTraversalV SET name = 'b'")).execute();
    db.command(new OCommandSQL("CREATE VERTEX testCyclicDeepTraversalV SET name = 'c'")).execute();
    db.command(new OCommandSQL("CREATE VERTEX testCyclicDeepTraversalV SET name = 'z'")).execute();

    // a -> b -> z
    // z -> c -> a
    db.command(new OCommandSQL("CREATE EDGE testCyclicDeepTraversalE from"
        + "(select from testCyclicDeepTraversalV where name = 'a') to (select from testCyclicDeepTraversalV where name = 'b')"))
        .execute();

    db.command(new OCommandSQL("CREATE EDGE testCyclicDeepTraversalE from"
        + "(select from testCyclicDeepTraversalV where name = 'b') to (select from testCyclicDeepTraversalV where name = 'z')"))
        .execute();

    db.command(new OCommandSQL("CREATE EDGE testCyclicDeepTraversalE from"
        + "(select from testCyclicDeepTraversalV where name = 'z') to (select from testCyclicDeepTraversalV where name = 'c')"))
        .execute();

    db.command(new OCommandSQL("CREATE EDGE testCyclicDeepTraversalE from"
        + "(select from testCyclicDeepTraversalV where name = 'c') to (select from testCyclicDeepTraversalV where name = 'a')"))
        .execute();

    // "bar" in the following query declares a dependency on the alias "baz", which doesn't exist.
    OSQLSynchQuery query = new OSQLSynchQuery(
        "MATCH " + "{ class: testCyclicDeepTraversalV, as: foo, where:(name ='a')}.out() {while: ($depth < 2), where: (name = 'z'), as: bar},"
            + "{ as: bar}.out() {while: ($depth < 2), as: foo}" + " RETURN $patterns");

    List<?> result = db.query(query);
    assertEquals(1, result.size());

  }
```

BTW, I'll add it to 2.2.x anyway, it was definitely missing

Thanks!

Luigi

**Comment by obi1kenobi** [comment]
I assume the `// "bar" in the following query declares a dependency on the alias "baz", which doesn't exist.` comment is erroneously left over from a copy-paste?

**Comment by luigidellaquila** [comment]
Ouch! Yes, sorry, just a copy-paste ;-)

**Comment by obi1kenobi** [comment]
@luigidellaquila I added your test case and some extra logic to cover it -- thanks for the help!

I think this scheduler is definitely an improvement over the old approach, and it passes all tests. Unless there are any remaining serious edge cases you can come up with, please consider releasing this in 2.2.14.

**Comment by obi1kenobi** [comment]
Fantastic, thank you! Let me know if you need help to merge these changes into the `develop` branch as well.

**Comment by luigidellaquila** [comment]
I merged them to develop today, I only have to check that they are correctly used by the new executor as well, but it's an easy task.

Thanks!

Luigi

**Pull request merged**
