### PR TITLE
added flag to disable transaction check for move vertex operations

### PR DESCRIPTION
**Pull request by wouterv**

### CODE REVIEW

**Comment by lvca** [comment]
@wouterv thanks for this PR. I'd prefer to remove this check at all and leave the responsibility to the user: using OrientGraphNoTx is faster (on atomic operations), but less safe. WDYT about updating this PR by removing the new global setting and just removing the check?

**Comment by wouterv** [comment]
@lvca agreed and done.

**Comment by lvca** [comment]
Perfect, thanks!

**Comment by luigidellaquila** [comment]
@lvca why was the NON_TX_CHECK_MOVE_VERTEX flag removed from the PR????
This is definitely unsafe!!!

Luigi

**Comment by lvca** [comment]
The reason is already here, read my comment above: https://github.com/orientechnologies/orientdb/pull/5926#issuecomment-209845849.

**Pull request merged**
