### PR TITLE
Used the same OModificationLock object of storage

### PR DESCRIPTION
**Pull request by lvca**
Used the same OModificationLock object of storage

### CODE REVIEW

**Comment by laa** [comment]
Luca we can not remove modification lock from index in 2.1
because indexes before 2.2 directly go to data structures and do not participate in storage modification lock it is fixed in https://github.com/orientechnologies/orientdb/issues/4831

**Comment by lvca** [comment]
I didn't remove modification lock in indexes, but I used the same object as for storage.

**Comment by laa** [comment]
Well probably it will work, let me think till tomorrow.

**Comment by laa** [comment]
@lvca could you trace all usages of prohibit modifications from indexes and remove them, so we will leave storage as central point of control, then I think we may merge pull request ?

**Comment by lvca** [comment]
So you mean to completely remove the usage of modification lock, right?

**Comment by lvca** [comment]
In all the indexes?

**Pull request closed without merging**
