### PR TITLE
shutdown needs to be before resetListener

### PR DESCRIPTION
**Pull request by rtm81**

### CODE REVIEW

**Comment by laa** [comment]
Could you provide pull request without code stile reformatting. It is hard to understand what was really changed.

**Comment by laa** [comment]
Did you move reset listeners at the end ?

**Comment by laa** [comment]
If that is only change I will apply it manually then.

**Comment by rtm81** [comment]
All i did: In method shutdown() i moved

      for (final WeakHashSetValueHolder<OOrientShutdownListener> wl : weakShutdownListeners)
          try {
              if (wl != null) {
                  final OOrientShutdownListener l = wl.get();
                  if (l != null)
                      l.onShutdown();
              }
              
          } catch (Exception e) {
              OLogManager.instance().error(this, "Error during orient shutdown.", e);
          }

before 
resetListeners();

**Comment by laa** [comment]
But "strong" listeners are still cleared before calling them.
Do you mind if we will do following move reset listeres bellow and revert rwspinlock cleanup I think it is not needed and main issue was absence of clean up on more high level object. Do not you mind to check it ?

**Comment by laa** [comment]
I merged changes manually.

**Comment by laa** [comment]
Thank you for your help !

**Pull request closed without merging**
