### PR TITLE
Issue 8207

### PR DESCRIPTION
**Pull request by markuskreusch**
PR regarding #8207 

I would recommend to remove the existing AES and DES implementations when this is integrated into 3.0.x. Those are really insecure and nobody should be using them. AES-GCM mode is hardware-accelerated starting from Java 9 - so will provide most performance for people using this.

This feature should also be included in the 2.x branch. Here removal of the existing implementations may not be an option due to compatibility. I marked OAESEncryption and ODESEncryption as deprecated but because users will never see this when using the configuration a prominent warning should maybe be printed to the logs if those are used for the 2.x branch to inform users about the security problems with the existing implementation.

Tests were executed as mentioned in the contribution guide. They failed at

> [ERROR] Errors: 
> [ERROR] com.orientechnologies.spatial.LuceneSpatialAutomaticBackupRestoreTest.shouldBackupAndRestore(com.orientechnologies.spatial.LuceneSpatialAutomaticBackupRestoreTest)
> [ERROR]   Run 1: LuceneSpatialAutomaticBackupRestoreTest.shouldBackupAndRestore:192 » Runtime j...
> [ERROR]   Run 2: LuceneSpatialAutomaticBackupRestoreTest.tearDown:130->dropIfExists:124 » ODatabase

but this also occurs on the develop branch. I do not assume that these changes broke something.

### CODE REVIEW

**Comment by tglman** [comment]
Hi @markuskreusch,

Very nice contribution, we are evaluating is inclusion as soon as possible.

Regards

**Comment by tglman** [comment]
Hi @markuskreusch,

Very nice contribution, we are evaluating is inclusion as soon as possible.

Regards

**Comment by tglman** [comment]
Hi,

I've been testing this, and when I run the test:OAESGCMEncryptionTest#testCreatedAESEncryptedDatabase i see the process get stuck for more than one minute on:
```
  java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424)
	at sun.security.provider.NativePRNG$RandomIO.ensureBufferValid(NativePRNG.java:525)
	at sun.security.provider.NativePRNG$RandomIO.implNextBytes(NativePRNG.java:544)
	- locked <0x00000007232fc798> (a java.lang.Object)
	at sun.security.provider.NativePRNG$RandomIO.access$400(NativePRNG.java:331)
	at sun.security.provider.NativePRNG$Blocking.engineNextBytes(NativePRNG.java:268)
	at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
	at com.orientechnologies.orient.core.encryption.impl.OAESGCMEncryption.randomNonce(OAESGCMEncryption.java:169)
	at com.orientechnologies.orient.core.encryption.impl.OAESGCMEncryption.encrypt(OAESGCMEncryption.java:88)
	at com.orientechnologies.orient.core.encryption.impl.OAESGCMEncryption.encrypt(OAESGCMEncryption.java:75)
```

Not sure what is the root reason for this (maybe my machine do not handle correctly the SecureRandom), but I expect this test to not get more than 1/2 seconds with encryption and less than 1 without, so something is not going smooth.

a minor thing, since 3.0 we have new API, I rewritten one of the tests with the new API, please consider to update the test as this:
```
@Test
  public void testCreatedAESEncryptedDatabase() {
    String buildDirectory = System.getProperty("buildDirectory", ".");

    final String dbPath = buildDirectory + File.separator + DBNAME_DATABASETEST;
    OFileUtils.deleteRecursively(new File(dbPath));
    OrientDBConfigBuilder builder = OrientDBConfig.builder();
    builder.addConfig(STORAGE_ENCRYPTION_METHOD, "aes/gcm");
    builder.addConfig(STORAGE_ENCRYPTION_KEY, "T1JJRU5UREJfSVNfQ09PTA==");
    OrientDB orientDB = new OrientDB("embedded:" + buildDirectory, builder.build());
    orientDB.create(DBNAME_DATABASETEST, ODatabaseType.PLOCAL);
    ODatabaseSession db = orientDB.open(DBNAME_DATABASETEST, "admib", "amind");
    try {
      db.command("create class TestEncryption");
      db.command("insert into TestEncryption set name = 'Jay'");

      try (OResultSet result = db.query("select from TestEncryption")) {
        Assert.assertEquals(result.stream().count(), 1);
      }
      db.close();
      orientDB.close();

      orientDB = new OrientDB("embedded:" + buildDirectory, builder.build());
      db = orientDB.open(DBNAME_DATABASETEST, "admib", "amind");
      try (OResultSet result = db.query("select from TestEncryption")) {
        Assert.assertEquals(result.stream().count(), 1);
      }
      orientDB.close();

      builder = OrientDBConfig.builder();
      builder.addConfig(STORAGE_ENCRYPTION_METHOD, "aes/gcm");
      builder.addConfig(STORAGE_ENCRYPTION_KEY, "invalidPassword");
      orientDB = new OrientDB("embedded:" + buildDirectory, builder.build());
      OSecurityException exception = null;
      try {
        orientDB.open(DBNAME_DATABASETEST, "admib", "amind");
      } catch (OSecurityException e) {
        exception = e;
      } finally {
        assertNotNull(exception);
      }
      orientDB.close();

      builder = OrientDBConfig.builder();
      builder.addConfig(STORAGE_ENCRYPTION_METHOD, "aes/gcm");
      builder.addConfig(STORAGE_ENCRYPTION_KEY, "T1JJRU5UREJfSVNfQ09PTA=-");
      orientDB = new OrientDB("embedded:" + buildDirectory, builder.build());

      exception = null;
      try {
        orientDB.open(DBNAME_DATABASETEST, "admib", "amind");
      } catch (OSecurityException e) {
        exception = e;
      } finally {
        assertNotNull(exception);
      }

      orientDB.close();

      builder = OrientDBConfig.builder();
      builder.addConfig(STORAGE_ENCRYPTION_METHOD, "aes/gcm");
      builder.addConfig(STORAGE_ENCRYPTION_KEY, "T1JJRU5UREJfSVNfQ09PTA==");
      orientDB = new OrientDB("embedded:" + buildDirectory, builder.build());
      db = orientDB.open(DBNAME_DATABASETEST, "admib", "amind");
      try (OResultSet result = db.query("select from TestEncryption")) {
        Assert.assertEquals(result.stream().count(), 1);
      }
      orientDB.close();
    } finally {
      builder = OrientDBConfig.builder();
      builder.addConfig(STORAGE_ENCRYPTION_METHOD, "aes/gcm");
      builder.addConfig(STORAGE_ENCRYPTION_KEY, "T1JJRU5UREJfSVNfQ09PTA==");
      orientDB = new OrientDB("embedded:" + buildDirectory, builder.build());
      orientDB.drop(DBNAME_DATABASETEST);
      orientDB.close();
    }
  }

```

If you have any problem let me know

Regards

**Comment by markuskreusch** [comment]
Ok, will update the tests accordingly.

That the process got stuck may indeed be caused by non available randomness used during encryption.
- Did you run this on Windows or a Linux machine? Which OS exactly?
- Is this run in a VM? Sometimes no randomness is available there at all and such systems need special packages installed to provide it (e.g. rng-tools or rng-utils).

**Comment by tglman** [comment]
Hi @markuskreusch,

If you can find a solution that do not block in case of failure is fine for me, even a timeout could be fine because we can give up a descriptive exception that make the people aware that they need to enable the native encryption or choose a different implementation.

Regards

**Comment by markuskreusch** [comment]
Hi @tglman 

I adressed the issues:
- Test now uses the implementation you provided.
- Using new SecureRandom() because that is well enough. Added a one minute timeout during initial seeding of the SecureRandom to check if it blocks. If it does an exception is thrown.

**Comment by tglman** [comment]
Hi @markuskreusch,

Looks fine ready to marge it, i prefer to not deprecate the old not completely secure implementations yet, they could be a viable basic solution (better than in clear) in environment where good encryption is not supported.

About everything else, is good to go.

Regards

**Comment by overheadhunter** [comment]
> Looks fine ready to marge it, i prefer to not deprecate the old not completely secure implementations yet, they could be a viable basic solution (better than in clear) in environment where good encryption is not supported.

Great, looking forward to the merge! :tada:

Yes, ECB mode is a bit better than no encryption at all. Still, marking the classes as deprecated doesn't do any harm. You as the maintainer of this project have full control over _when_ you want to remove it. Maybe OrientDB 4.0, maybe 5.0... I think deprecation warnings are a good means to make users switch to an improved implementations, if they have the choice. If they don't they can stick with ECB, of course.

**Comment by lvca** [comment]
@markuskreusch and @overheadhunter thanks for this PR! Are you using OrientDB in any project?

**Comment by overheadhunter** [comment]
@lvca Yes, we're using OrientDB with GCM as a an encrypted file metadata store for [Defendor](https://defendor.skymatic.de/en/). It's still under development and the project name might change, though. 🙂

**Comment by lvca** [comment]
@overheadhunter very cool, when you guys are live, WDYT about telling your story in a case study?

**Comment by overheadhunter** [comment]
@lvca Yes, sure! We'll ping you when we're ready!

**Pull request merged**
