### PR TITLE
Update dserver.sh to allow ./some/path/to/dserver.sh

### PR DESCRIPTION
**Pull request by vitorenesduarte**

### CODE REVIEW

**Comment by lvca** [comment]
Vitor, what's the goal of this change?

**Comment by vitorenesduarte** [comment]
It's only possible to run dserver.sh from __ORIENTDB_HOME/bin__ folder.
As it's possible to run server.sh from anywhere, I think dserver.sh should also be.
It's just a suggestion. You probably have a better way to do this.

**Comment by lvca** [comment]
Sounds good. May you do it against "develop" branch? We use master only for releasing. Thanks.

**Comment by lvca** [comment]
Waiting for new PR ;-)

**Comment by vitorenesduarte** [comment]
#3569 Don't know If I did it right.

**Comment by vitorenesduarte** [comment]
#3570 Sorry for the three PR. I think now it's ok.

**Pull request closed without merging**
