### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by rmuller**
Now made PR against 2.0.2-hotfix. Note my other PR is also included. Do not know how to prevent this :(

### CODE REVIEW

**Comment by lvca** [comment]
No problem, I can merge it manually. Thank!

**Comment by lvca** [comment]
Done ;-)

**Comment by rmuller** [comment]
you are soooo fast :) nice!

**Comment by lvca** [comment]
Propagated also to "develop" -> 2.1-SNAPSHOT.

**Pull request merged**
