### PR TITLE
Issue default value

### PR DESCRIPTION
**Pull request by matanshukry**
Same pull request as #3646 , only merged develop branch, and making a pull request against it - as requested

### CODE REVIEW

**Comment by lvca** [comment]
This fixes issue #665

**Comment by matanshukry** [comment]
Added a simple test case; it works for both a function and a constant.

**Comment by lvca** [comment]
Thanks!

**Comment by tglman** [comment]
hi,
all the test where failing, i had to revert it :( 
in particular where breaking the required validation.

**Comment by lvca** [comment]
Which tests? I tried and worked.

**Comment by matanshukry** [comment]
I am having problem running the tests, sorry for not checking that before.
I managed to run a specific one now and saw the problem, also fixed it and pushed, but can't see it here. Do I need to open a new pull request?

**Pull request merged**
