### PR TITLE
fix for #3427. Added test case.

### PR DESCRIPTION
**Pull request by fabriziofortino**

### CODE REVIEW

**Comment by fabriziofortino** [comment]
@lvca can this be merged?

**Comment by lvca** [comment]
It's impossible to see what you changed in ORecordLazyList.java. Is it a formatting problem?

**Comment by fabriziofortino** [comment]
I think so. I have just removed an unused import.

**Comment by lvca** [comment]
Ok, merging anche checking it right after.

**Comment by lvca** [comment]
Thanks, as always ;-)

**Comment by nagarajasr** [comment]
@lvca my 2c, in case you are using the github web interface to see the diff, add ?w=1 at the end of the URL to ignore whitespace in the comparison, using that, i can clearly see that there was only 1 line change to remove the unused import.

**Comment by lvca** [comment]
`?w=1` works, thanks!

**Pull request merged**
