### PR TITLE
Added fixes for auth timing attacks for OrientDB 2.1.x

### PR DESCRIPTION
**Pull request by obi1kenobi**
Pull request for authentication vulnerabilities -- timing attacks on password and digest checks.

Addresses concerns raised in #5611 and #5597.

### CODE REVIEW

**Comment by obi1kenobi** [comment]
I had some Maven difficulties running the tests, and I wasn't able to run the tests locally. Please make sure the tests pass before merging?

**Comment by lvca** [comment]
Thanks @obi1kenobi, I'm checking it right now...

**Comment by lvca** [comment]
2.1.x branch seems good now. Checking it on it, your PR don't pass.

**Comment by obi1kenobi** [comment]
Do you mind posting the error log of why the PR doesn't pass? Also, not sure I understand what you mean by "the 2.1.x branch seems good now."

**Comment by lvca** [comment]
The 2.1.x branch builds: http://helios.orientdb.com/job/orientdb-2.1.x/. So you could pull form 2.1.x and retry "mvn clean test"

**Comment by obi1kenobi** [comment]
I was able to pull and rebase onto the 2.1.x branch and verify that all tests pass with the updated code. Thanks!

**Comment by lvca** [comment]
That was perfect, thanks!

**Comment by obi1kenobi** [comment]
Great, thanks for merging. Any thoughts on when this will become part of a new release?

**Comment by lvca** [comment]
Next hotfix should be scheduled for the next week.

**Pull request merged**
