### PR TITLE
Issue 89, AES and DES encryption at rest

### PR DESCRIPTION
**Pull request by giastfader**
This PR is related to https://github.com/orientechnologies/orientdb/issues/89
Here are two new cluster compression methods that use AES and DES to encrypt data.
Keys have to be declared into the configuration file, or in any other way supported by OrientDB (command line, direct set on OGlobalConfiguration enumerator).
There is of course room for improvements, consider this as a first WORKING implementation.

usage:
```
create class aes
alter cluster aes compression aes-encrypted

create class des
 alter cluster des compression des-encrypted
```

### CODE REVIEW

**Comment by lvca** [comment]
We're in RC phase, I'll merge this as soon as we start the 2.2-SNAPSHOT.

**Comment by lvca** [comment]
Hey @giastfader I was merging this in develop, but unfortunately you didn't sign the clahub agreement (for the Apache2 license). Please could you do that? Thanks in advance.

**Comment by lvca** [comment]
Waiting for you to electronic signing the CLA, I saw you use 2 new global settings:
```java
STORAGE_ENCRYPTION_DES_KEY("encryption.des_key","The simmetric key to use to encrypt/descript data at rest using the DES alghorithm, stored in BASE64. The key must be 64 bits long. Default is \"T1JJRU5UREI=\" (ORIENTDB).",String.class,"T1JJRU5UREI="),
 STORAGE_ENCRYPTION_AES_KEY("encryption.aes_key","The simmetric key to use to encrypt/descript data at rest using the AES alghorithm, stored in BASE64. The key must be 128 or 256 bits. Default is \"T1JJRU5UREJfSVNfQ09PTA==\" (ORIENTDB_IS_COOL).",String.class,"T1JJRU5UREJfSVNfQ09PTA=="),
```

I think it would be much better don't setting any password by default and check if password is null, an exception is raised. In this way the user can't do mistakes. WDYT?

**Comment by giastfader** [comment]
Yes, I agree, if you want to force the admin to explicitly set a key.

**Comment by lvca** [comment]
Cool, I'm merging it right now

**Comment by lvca** [comment]
Done, thanks!

**Pull request merged**
