### PR TITLE
object api performance improvements case #5443

### PR DESCRIPTION
**Pull request by wouterv**

### CODE REVIEW

**Comment by lvca** [comment]
Hey @wouterv, did you check all tests pass?

**Comment by wouterv** [comment]
Up to server they did, but there was something wrong in the server module
that seemed unrelated to me..
Op 9 dec. 2015 9:56 p.m. schreef "Luca Garulli" <notifications@github.com>:

**Comment by wouterv** [comment]
@lvca I just did a clean checkout of the 2.1.x branch (without these changes) and the same failures occur, so the problem is probably not in my changes.

**Comment by wouterv** [comment]
@lvca ok it looks like the server module just builds using travis, but if you look at the log, somehow the jvm got killed while running orient-tests, I tried to run from the orient-tests module locally with my changes (first did mvn -DskipTests clean install, then mvn clean install -rf :orient-tests), and it doesn't get killed, it builds fine.

**Comment by lvca** [comment]
Yes, Travis kills all the build with exec time >20mins. We're replacing it with CloudBee.

**Comment by wouterv** [comment]
@lvca is there anything else you need for this pull request

**Comment by tglman** [comment]
Hi @wouterv,

This solution use static variable, will be cool if you can move this implementation in some instance linked to OEntityManager ?

**Comment by wouterv** [comment]
@tglman I don't understand, the info stored is static, class information like fields and so on, why do you want to link it to an instance?

**Comment by tglman** [comment]
In some environment like inside an application server or an OSGI environment use static fields can bring to problems, we have some configuration for handle some of this cases for OSGI, so is better not introduce additional static variable and use the existent one, and anyway one of the responsibility of OEntityManager is to handle class definition.

**Comment by wouterv** [comment]
I get the point about OSGi, I will make a rewrite using the OEntityManager.

**Comment by wouterv** [comment]
@tglman Would using OObjectEntitySerializer.OObjectEntitySerializedSchema a good place to put the caches? Looks like it is already done like that for some other stuff.

**Comment by tglman** [comment]
@wouterv yes

**Comment by wouterv** [comment]
@tglman @lvca created new pull request for this: #5462

**Pull request closed without merging**
