### PR TITLE
replaced hashcode() with getIdentity() as indentifier in the map of

### PR DESCRIPTION
**Pull request by thewall13**
already detached objects

### CODE REVIEW

**Comment by tglman** [comment]
hi @thewall13  this look good, does all the tests pass with this ?

**Comment by thewall13** [comment]
the detached-tests worked fine. I have three test-failures with "ant test" but it doesn't seems to be something with these changes.

I only switched the key in the map, so everything should work fine.

**Comment by thewall13** [comment]
Here is the missing related issue: https://github.com/orientechnologies/orientdb/issues/3561

**Comment by wouterv** [comment]
I can confirm I had problems with this issue (which I introduced) and that this pull request fixes it. I have no clue why I used hashCode in the first place...

So I hope it can be merged into 2.0.3!

**Comment by lvca** [comment]
Merged. Thanks guys. I'm backporting it to 2.0.3...

**Pull request merged**
