### PR TITLE
added initial .travis.yml

### PR DESCRIPTION
**Pull request by krichter722**
see #4701

### CODE REVIEW

**Comment by lvca** [comment]
Thanks.

**Comment by krichter722** [comment]
If you register orientechnologies at travis-ci.org, you can activate checks for every PR and all members.

**Comment by lvca** [comment]
We didn't use Travis anymore because we have Jenkins at helios.orientdb.com. However, I've re-activated Travis support because the PR ;-) Thanks.

**Comment by krichter722** [comment]
In case it ever falls behind the requirements of `orientdb` build and test process or support is re-dropped for another reason, the content of `.travis.yml` can be changed to `exit 1` and a comment could be added in order to indicate that the service has been taken into consideration.

**Pull request merged**
