### PR TITLE
Default values prepopulation. For issue #4535

### PR DESCRIPTION
**Pull request by PhantomYdn**

### CODE REVIEW

**Comment by lvca** [comment]
WDYT about pre-populate them on setClass() and setClassname() ?

**Comment by PhantomYdn** [comment]
In this case I personally don't like a side effect: if class was set twice - class will have default values also from first class populated...

**Comment by lvca** [comment]
You're right, but semantically these 2 calls should produce the same effect:
```java
new ODocument("Person");
new ODocument().setClassname("Person");
```

**Comment by PhantomYdn** [comment]
@lvca agreed! PR has been updated with recent code. Please take a look into testcase for all supported cases.

**Comment by PhantomYdn** [comment]
Guys? Build is failing due to timeout. Local test is fine.

**Comment by lvca** [comment]
Perfect, merging it now. Thanks.

**Pull request merged**
