### PR TITLE
added the possibility to register recursive classes and attribute classe...

### PR DESCRIPTION
**Pull request by svenruppert**
added the possibility to register recursive classes and attribute classes from a start point ( class)
So no need to have all classes in the same (sub)-package.

### CODE REVIEW

**Comment by lvca** [comment]
Cool, thanks!

**Comment by svenruppert** [comment]
thx ;-)

**Comment by PhantomYdn** [comment]
Imho, quite dangerous method to invoke. I recommend avoid at least "transient" fields.

**Comment by PeterKnego** [comment]
No tests? Seriously guys..

**Comment by lvca** [comment]
@svenruppert please could you add a test case on it and take in consideration the comment from @PhantomYdn ?

**Pull request merged**
