### PR TITLE
Fixed NPE when trying to update a vertex that has an rid bag

### LINKED ISSUE #9179: [Bug] [3.1.0] [works in 3.1.0-M3] [Client] NPE on updating vertex after edge exist
## Expected behavior
Not to throw an NPE

## Actual behavior
throw an npe.
Stacktrace:

```
java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaLinkBag(ODocumentSerializerDelta.java:607) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaValue(ODocumentSerializerDelta.java:585) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDeltaEntry(ODocumentSerializerDelta.java:558) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDelta(ODocumentSerializerDelta.java:542) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ODocumentSerializerDelta.serializeDelta(ODocumentSerializerDelta.java:66) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.client.remote.message.OCommit38Request.<init>(OCommit38Request.java:65) ~[orientdb-client-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1009) ~[orientdb-client-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2326) [orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:554) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:105) ~[orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1882) [orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1852) [orientdb-core-3.1.0-beta1.jar:3.1.0-beta1]
```

I can also add that `timeline` variable was null in there.

## Steps to reproduce  

- The NPE happens when I run a software I made that creates 100 vertices and then creates, and then for each one creates 1-5 (random) edges between them.
- Each call is, both to create the vertices and the edges, is separate and has a `.begin()` before it and `.commit()` after it
- the query it self isn't that complex, it uses 2 sub select to choose the vertices and set some data, nothing too special

## Notes

As mentioned in the title, there is no NPE when using the older version `3.1.0-M3`

### PR DESCRIPTION
**Pull request by matanshukry**
Such a small difference yet it solves a really huge bug.

This fixed a bug that should be marked as high priority and should probably be pushed as a hotfix (after review that is)

Fixed #9179

### CODE REVIEW

**Comment by matanshukry** [comment]
I've re-ran those tests the CI says are failing and they are running successfully locally on my computer (same branch).

Am I missing something?

**Comment by matanshukry** [comment]
Any updates on this?

@tglman

**Comment by tglman** [comment]
This is good, I'm double checking it and i will merge it soon, do you have a reproducer to the problem so we do not reintroduce the problem in future ?

**Comment by matanshukry** [comment]
@tglman Not familiar enough with the tests to answer that, but when running the console you can simply create an edge between 2 vertices and then trying to update any of the vertices will result in this bug

**Comment by tglman** [comment]
merged by hand, closing this

**Pull request closed without merging**
