### PR TITLE
Add ability to specify "description" for OClass and OProperty

### PR DESCRIPTION
**Pull request by PhantomYdn**
Guys,

There is no way to store some documentation about OClass or OProperty. But almost all relational DB has the place for that, for example PostgreSQL and Oracle has "comment" field and so on.
I propose to add new field for OClass'es and OProperties'es: "description".

This commit contains initial implementation. Please let me know if you have any concerns. Also I will appreciate if you can point me out to any impacted places, where corresponding changes should be done too. For example: cli-console(?), web-console(?) etc.

P.S. Build is failing due to existing problem in a "develop" branch. It doesn't relate to this functionality.

### CODE REVIEW

**Comment by PhantomYdn** [comment]
Guys?

Any thoughts on applying this PR? It will have keep documentation right in DB.

**Comment by lvca** [comment]
@PhantomYdn, thanks for this high-quality contribution (again). This is an enhancement and we're in RC phase, so I can merge it as soon as we .switch to 2.2-SNAPSHOT (few days)

**Comment by PhantomYdn** [comment]
Sure! Once 2.2-SNAPSHOT appear I will merge and resolve current conflicts.

In a meanwhile: I guess ability to document OClass and OProperty should be introduced in several places:
1) OrientDB Studio
2) Console
What else?

**Comment by lvca** [comment]
@maggiolo00 can take care of studio

**Comment by lvca** [comment]
Hey @PhantomYdn This PR seems perfect. Unfortunately seems it goes in conflict with current develop branch (now 2.2.0-SNAPSHOT). Please could you fix conflict and update it? Thanks in advance.

**Comment by PhantomYdn** [comment]
@lvca , PR has been updated

**Comment by PhantomYdn** [comment]
Guys? Build is failing due to timeout. Local test is fine.

**Comment by lvca** [comment]
Thanks, again ;-)

**Pull request merged**
