### PR TITLE
OClassTrigger should become aware about multiple superclasses

### PR DESCRIPTION
**Pull request by PhantomYdn**
This is fix for issue #6092 
Also it introduce new feature to get custom value from OClass taking into account hierarchy
Please consider to merge to 2.2.1

### CODE REVIEW

**Comment by tglman** [comment]
hi @PhantomYdn,
the pool request seems ok, two points though:
I don't like to add new public API at this point of the release process, so i think is better add this API just to OImmutableClass and open another issue to evaluate how to make public consistent API for this specific case.  
I would like a test case ;)

**Comment by PhantomYdn** [comment]
I can add test case - no problem:)
@tglman , @lvca , but can we please agreed about adding  String getCustomHierarchical(...) methods to API? It's just adding: no changes for existing methods. As I wrote it will help a couple of related issues which rely to "custom" fields.

**Comment by PhantomYdn** [comment]
Guys, any thoughts? Is it possible to add those methods to OClass?

**Comment by PhantomYdn** [comment]
According to Code 2.2 multiple hierarchy is being now supported. Closing as outdated.

**Comment by lvca** [comment]
Thanks.

**Pull request closed without merging**
