### PR TITLE
Revert "Initial implementation for #5360.  Enhances the CREATE Property syntax."

### PR DESCRIPTION
**Pull request by luigidellaquila**
Reverts orientechnologies/orientdb#5361

Sorry, I have to revert this PR, because it makes the grammar inconsistent. 
Consider the following:
```
CREATE PROPERTY Foo.bar LINK MANDATORY
```

Does the `MANDATORY` refer to the linked class (it is a valid class name) or to the Mandatory attribute?

We need to find a better solution for the syntax.

Thanks

Luigi

### CODE REVIEW

**Comment by smolinari** [comment]
Make "Mandatory" a reserved word?

Scott

**Comment by luigidellaquila** [comment]
Yes, it could be a good idea, but we already have a bunch of reserved words, and every time I add a new one someone will have problems with backward compatibility...

I'll see what I can do

Thanks

Luigi

**Comment by smolinari** [comment]
Well, a data model with a class named "mandatory" sounds rare to me. And sometimes BC needs to take a back seat to good new functionality. :wink: 

Scott

**Comment by smolinari** [comment]
Though, things that break BC shouldn't happen in minor updates either. Only major point releases or higher, like in the upcoming 2.2 release.

Scott

**Pull request merged**
