### PR TITLE
Default values feature added

### PR DESCRIPTION
**Pull request by matanshukry**
Added default value feature. Usage example:

> CREATE CLASS People
> CREATE PROPERTY People.alive DEFAULTVALUE true
> INSERT INTO People SET name="Joe Smith", age=24

> SELECT FROM People
will show the column 'alive' with value 'true'.

Note that I am not too familiar with OrientDB code, so I hope I managed to change all the relevant code - please review this carefully!

Relevant issues:
#665
#1999

### CODE REVIEW

**Comment by phpnode** [comment]
@matanshukry this is awesome, people have asked for this a LOT. Could we call it `DEFAULT` instead of `DEFAULTVALUE` though? it'd bring it in line with other databases.

**Comment by tglman** [comment]
yes, it's a good feature.
can you do a pull request against the develop branch?
a couple of test cases on the feature are not a bad idea ;)


@luigidellaquila is it easy allow thin in the new parser ?

**Comment by lvca** [comment]
@matanshukry awesome contribution!

**Comment by luigidellaquila** [comment]
@tglman yes, it's trivial.
Anyway it should not impact the state of the art, because at this stage the new parser only covers CRUD operations, not schema manipulation.

**Comment by matanshukry** [comment]
Renamed DEFAULTVALUE to DEFAULT as requested;
Also changed a bit so that functions can now work; Example:

> CREATE CLASS People
> CREATE PROPERTY People.join_date DATETIME
> ALTER PROPERTY People.join_date DEFAULT sysdate()
> INSERT INTO People SET name="Kait"

Note: I checked it with only two rows, but it works as expected; the sysdate() is evaluated on insert.

**Comment by phpnode** [comment]
@matanshukry this is great, a really necessary feature

**Comment by matanshukry** [comment]
Merged the develop branch and created another pull request against it (points to this one). Please continue any further discussion in there:
#3649

**Comment by fabriziofortino** [comment]
@matanshukry that's really cool!

I think this PR is related to #665 

It would be nice to execute a function to set the default value. Something like:
CREATE PROPERTY myclass.timestamp DEFAULT sysdate();

**Comment by tglman** [comment]
any volonteer to add test cases on top of that ?

**Pull request closed without merging**
