### PR TITLE
Rid-bags serialization optimization

### PR DESCRIPTION
**Pull request by markodjurovic**
New rid-bags serializers using varints instead of fixed size length fields.
Introduced new rid-bags serializers' abstraction layer.

### CODE REVIEW

**Comment by lvca** [comment]
Great! Is it compatible with the previous versions? Are we keeping both serializers?

**Comment by markodjurovic** [comment]
Both serializers are present, so it is backward compatible. Old one is still default serializer.

**Comment by lvca** [comment]
Cool, thanks. @tglman when can we enable as default all those changes by Marko?

**Comment by laa** [comment]
I have a question, do we have any number form usage of both serializers?

**Comment by tglman** [comment]
Hi all,

we actually had a private discussion we are going to simplify this changes, so probably this PR will be closed, the performance difference in term of cpu I don't think is going to be big, in term of size we will have an average of 50% less memory for the same content.

Regards

**Comment by lvca** [comment]
@tglman how much time to redo this? Can we put this in v3.0 and change the impl later in some hotfix?

**Comment by laa** [comment]
@tglman as I understand you do not have results of any measurements at this moment, is it possible to send numbers before and after implementation in terms of space and performance?

**Comment by markodjurovic** [comment]
After conversation with @tglman we came to the conclusion that it can be done in another simpler way.

**Pull request closed without merging**
