### PR TITLE
Spatial improvements (st_distance)

### PR DESCRIPTION
**Pull request by matanshukry**
This fixes is something I need so t would be great to have it.

The idea is that now we can execute a query with distance function the same way I did with shortestPath. Example:

```
SELECT shortestPath(other.@RID, (SELECT FROM user WHERE userId='msh'), null, "Like", {"maxDepth": 4}) as path, st_distance(other.locationCoordinates, (SELECT locationCoordinates FROM user WHERE userId='msh')) as distance FROM (SELECT out as other FROM Like where in.userId = 'msh')
```
In it you can see both the use of shortestPath (which is currently working) and the use of st_distance (which will currently result in an exception this will fix).

Commit message:
```
- extracted OSQLFunctionShortestPath code to a common function 'getSingleItem' in parent class
- Also aded 'getSingleProperty' on the same idea
- Moved 'OShapeFactory factory' from class 'OSpatialFunctionAbstractIndexable' to parent 'OSpatialFunctionAbstract'
- OSTDistanceFunction now inherts from 'OSpatialFunctionAbstract' instead of 'OSQLFunctionAbstract'
- Added 'toShape' method in OSpatialFunctionAbstract to ease the conversion from a param to a shape. It follows the idea of what is done in OSQLFunctionShortestPath::execute
- OSTDistanceFunction and OSTDistanceSphereFunction use new 'toShape' method
```

### CODE REVIEW

**Comment by matanshukry** [comment]
Any news on this? This is (or #9191) is a major feature for me and I'm currently only using docker versions (3.0.30) - would love to see this in the upcoming version.

**Comment by wolf4ood** [comment]
Hi @matanshukry 

i will check it. Meanwhile are you able to provide also a unit test for this usage in the `shortestPath` ?

Thanks

**Comment by matanshukry** [comment]
@wolf4ood Not sure what you're talking about? This PR has no actual changes to `shortestPath`. The code changes in there was simply extracting code to a function so it can used outside in another class as well

**Comment by wolf4ood** [comment]
Hi @matanshukry  not in the shortest path test, but in the spatial one. Since it's kind of new improvement / feature it would be cool to have a test that cover eventual regression.

But it's ok i can do it later. Meanwhile could you check this one. Seems to be failing 1 of the lucene tests

https://travis-ci.org/github/orientechnologies/orientdb/builds/667988682#L2780

Thanks :)

**Comment by matanshukry** [comment]
@wolf4ood fixed

**Comment by matanshukry** [comment]
@wolf4ood that was quick, thanks!
On a side note: Can you estimate when will this feature be released to a docker image? Is there anything I can do to help hasten the process?

**Comment by wolf4ood** [comment]
Hi @matanshukry 

this is no in develop branch which is the next 3.1. release. Which for now we don't produce i think docker for snapshot. I'm not sure when the final GA will be out yet.

Are you using the 3.0.x releases? Do you need it there?
In case i need to backport it 

Thanks

**Comment by matanshukry** [comment]
@wolf4ood yeah I was talking about the 3.0.x releases
I'm currently using `orientdb:3.0.30`

**Comment by matanshukry** [comment]
@wolf4ood Is there anything I can do to help with the backport and/or with the advance of the develop branch to a new 3.0.x release?

**Comment by wolf4ood** [comment]
@matanshukry 

let me backport it to 3.0.x

Thanks

**Comment by wolf4ood** [comment]
Hi @matanshukry 

backported. It will be availabe in the next 3.0.x release or snaphost

Thanks

**Comment by matanshukry** [comment]
@wolf4ood cool thanks for both the work and notifying me!
Is there a release date or set of features waiting for the next release?

**Pull request merged**
