### PR TITLE
GraphSON

### PR DESCRIPTION
**Pull request by Blondysinger**
New Interface IGraphSONIterable

The change allows GraphSONUtility to use any kind of type that implements IGraphSONIterable. In this way not only List, Map, Array or Element, but all the wrapper that implements IGraphSONIterable, such as OrientElementIterable, will return a valid value from the jsonFromElement method.

### CODE REVIEW

**Comment by lvca** [comment]
How can GraphSONUtility use this interface if it's brand new ?

**Comment by Blondysinger** [comment]
Yes, sorry! You are right!
I've also modified blueprints libs in the method createJSONMap (GraphSONUtility) so that it too can recognize the interface.
Therefore you can benefit from this feature only if this interface will be accepted via the PR I've made in tinkerpop.

**Comment by Blondysinger** [comment]
I have modified the PR. OrientIterable doesn't need any change.

**Comment by lvca** [comment]
I don't see any changes. Can I close it?

**Pull request closed without merging**
