### PR TITLE
added initial .travis.yml

### PR DESCRIPTION
**Pull request by krichter722**

### CODE REVIEW

**Comment by lvca** [comment]
What's the reason of this PR?

**Comment by krichter722** [comment]
It allows the project to run on the [travis CI service](https://travis-ci.org) which checks all PRs and commits on a configurable set of branches. It's for free, helps to spot errors and doesn't do any harm.

**Comment by lvca** [comment]
Ok for me, but please send it to "develop" branch, not "master" that we use for release only. Thanks in advance.

**Comment by krichter722** [comment]
see #4746

**Pull request closed without merging**
