### PR TITLE
Initial implementation for #5360.  Enhances the CREATE Property syntax.

### PR DESCRIPTION
**Pull request by mmacfadden**
Unit tests seem to be passing for #5360

### CODE REVIEW

**Comment by mmacfadden** [comment]
This is failing due to what appears to be a JVM crash during the JDBC driver build.  The build works fine locally for me.  I can't imaging how this would have affected the JDBC driver.  There are several other PRs that are failing due to the same error, so I am confident this PR is actually clean.

**Comment by lvca** [comment]
@luigidellaquila Please check the PR ;-)

**Comment by mmacfadden** [comment]
I noticed that there was a lot of stuff merged into develop, so I re-merged this branch so it can be merged.

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

The PR seems to be ok.
One of the test cases is for LiveQuery (not related at all with your commit), I'm fixing it and then I'll rebuild you PR on Travis.

Thanks

**Comment by mmacfadden** [comment]
@luigidellaquila Thanks. Let me know if there are any issues, and I will address immediately.

**Comment by mmacfadden** [comment]
I just merged the latest code.  It seems like there is still an issue with the JDBC driver tests.

**Comment by mmacfadden** [comment]
Any updates on this pul request?

**Comment by luigidellaquila** [comment]
Hi @mmacfadden 

I merged it, thank you very much!
The CI keeps failing for reasons that are completely unrelated to your PR

Thanks a lot!

Luigi

**Pull request merged**
