### PR TITLE
edit OrientDB license info so that GitHub recognizes it

### PR DESCRIPTION
**Pull request by eirinikos**
Hello! 👋

(CCing @dankohn who has requested this work so that the license will appear correctly in
https://landscape.cncf.io/selected=orient-db)

GitHub uses a library called Licensee to identify a project's license
type. It shows this information in the status bar and via the API if it
can unambiguously identify the license.

This commit modifies a few of OrientDB's docs so that Licensee is able
to recognize the repository's license type. It renames the Apache license
file to LICENSE and replaces its contents with the full text of the
Apache license. It also moves the info concerning 3rd-party software
to a new "Licensing" section in the README.

Collectively, these changes allow Licensee to successfully identify the
license type of OrientDB as Apache 2.0.

For comparison purposes, here is the output that I get when I run Licensee locally on OrientDB's remote repo:
```
$ licensee detect https://github.com/orientechnologies/orientdb/
License:        Other
Matched files:  license.txt, ODB-ASL-LICENSE.txt
license.txt:
  Content hash:  72bd30cd5a7d4d3b164171521cc25132decf304b
  License:       Other
  Closest licenses:
    Apache-2.0 similarity:  95.15%
    ECL-2.0 similarity:     92.46%
    EPL-2.0 similarity:     55.37%
ODB-ASL-LICENSE.txt:
  Content hash:  d70e5d500315df2a25cfa7b3e57e93afe151ba97
  Attribution:   Copyright 2010-2016 OrientDB LTD (http://orientdb.com)
  License:       Other
  Closest licenses:
    Unlicense similarity:  36.78%
    Zlib similarity:       33.33%
    MIT similarity:        31.17%
```

And here is the output that I get when I run Licensee on the `update-license` branch of my local OrientDB clone:
```
$ licensee detect ../orientdb/
License:        Apache License 2.0
Matched files:  LICENSE
LICENSE:
  Content hash:  4f3dee90d3ff02d566b067c25982c2bfd7e360c1
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       Apache License 2.0
```

### CODE REVIEW

**Comment by lvca** [comment]
Thanks, really appreciated.

**Comment by luigidellaquila** [comment]
Sorry, I had to revert it.
This change broke the build, some bundling scripts explicitly pointed to license.txt file.
We can re-apply it also includes changes to the scripts

**Comment by luigidellaquila** [comment]
For reference http://helios.orientdb.com/job/orientdb-multibranch/job/develop/1421/console

**Comment by eirinikos** [comment]
> Sorry, I had to revert it.
This change broke the build, some bundling scripts explicitly pointed to license.txt file.
We can re-apply it also includes changes to the scripts

OK, I see. 👍 Where do the bundling scripts live?

**Comment by luigidellaquila** [comment]
Hi @eirinikos 

You'll find a reference to ODB-ASL-LICENSE.txt in the main pom.xml, plus a couple of references to license.txt in the "distribution" module, in the src assembly

Thanks

Luigi

**Comment by eirinikos** [comment]
Thanks @luigidellaquila. I think I understand what needs to be done now. I think part of my previous confusion was due to the fact that I was checking against the `master` branch, not the `develop` branch. I'm going to open a new PR that references this one.

**Pull request merged**
