### PR TITLE
Another version of the dijkstra function: dijkstra2

### PR DESCRIPTION
**Pull request by mbhulin**
As discussed in issue #4497 dijkstra2 is a copy of the original dijkstra function with the following changes:
* dijkstra2 has 4 or 5 parameters, dijkstra has 3 or 4 parameters 
* The third parameter is the edge type i. e. the subclass of E considered for routing. Other edges are neglected in dijkstra2.
* The fourth parameter is the name of the property that represents the 'weight' or 'cost'. In the original dijkstra function this is the third parameter.
* The optional direction parameter is the fifth parameter in dijkstra2 but the fourth parameter in dijkstra.
* If an edge has no weight field or the weight field is null this edge is not considered for routing, becouse the weight is set to Float.MAX_VALUE. In contrast the original dijkstra function sets the weight to zero in this case.
* If source and destination coincide return a path with only one vertex regardless whether a self-loop exists. This feature of dijkstra2 can be discussed: On one hand in a routing task if source and destination are the same you can reach the destination without effort. On the other hand there is no path with edges from source to destination.

There is also a new JUnit test OSQLFunctionDijkstraTest2 for the dijkstra2 function copied from OSQLFunctionDijkstraTest with additional test cases. All tests succeed.

### CODE REVIEW

**Comment by lvca** [comment]
Thanks @mbhulin, @luigidellaquila will review it. I'd prefer to change the original dijkstra() function adding custom parameters in form o JSON. Example:

```js
dijkstra({sourceVertex:#2323:32, destinationVertex:#232:23, edgeType:"Knows", weightEdgeFieldName:"since", direction:"OUT"})
```

In this way we can add feature to functions without break the signature. WDYT?

**Comment by mbhulin** [comment]
Hi Luca, 
I considered to have only one dijkstra funktion, the original one with 3 or 4 parameters and overload it with the new one with 5 parameters. The 5th argument then would be the edgeType. However a user might be confused by the different handling of edges which have no weight-field: In the original version an edge without the weight field is the ideal connection with zero cost, in the overloaded version an edge without the weight field is the worst connection with Float.MAX_VALUE as cost.

In order not to hide this difference I suggested two versions. Of course your suggested solution is possible, too. It has the advantage that you don't have a lot of similar functions dijkstra, dijkstra2, dijkstra3, ... I think it's your decision.

**Comment by lvca** [comment]
@mbhulin I really don't like the idea of having different dijkstra functions with a different number to differentiate them. If the original dijkstra() considered no weight as 0 (the best), it's a bug IMHO. So I'd prefer to have one-more-powerful dijkstra() function ;-) The problem is managing optional params in better way. We could pass a JSON, but I'm not sure the SQL parser would eat it correctly.

**Comment by w3aponx** [comment]
Other variants I could think of would be to have a list of allowed edge
types (instead of a single one), possibly with different cost depending on
edge class, and with the ability to allow sub-classes of the specified edge
classes or not.

On Mon, Aug 24, 2015 at 12:27 PM, Luca Garulli <notifications@github.com>
wrote:

> @mbhulin <https://github.com/mbhulin> I really don't like the idea of
> having different dijkstra functions with a different number to
> differentiate them. If the original dijkstra() considered no weight as 0
> (the best), it's a bug IMHO. So I'd prefer to have one-more-powerful
> dijkstra() function ;-) The problem is managing optional params in better
> way. We could pass a JSON, but I'm not sure the SQL parser would eat it
> correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/pull/4694#issuecomment-134289625>
> .
>



-- 
_____________
Mario Cormier

**Comment by gg4u** [comment]
Hi, as a user, I would also be interested in using djikstra with reversed weight, that is, instead of cheapest, most expensive weight.

Is the new function already based in master? Is documentation updated?
I'd like to try it.
Also, customed parameter 'weight' is a good thought.

**Comment by mbhulin** [comment]
@lvca If you think that the behaviour of the original dijkstra function to set "no weight" = "weight 0" is a bug the solution is easy. I also regarded this behaviour as bug but in the description it is explicitly specified: "* If property is not defined in edge or is null, distance between vertexes are 0." The question is whether there are already users who use the dijkstra funktion and rely on the specified behaviour.
Solution, if original dijkstra function may be changed:
* dijkstra(sourceVertex, destinationVertex, weightEdgeFieldName)
All edges with "weightEdgeFieldName" are considered with default direction OUT. If this field is missing or NULL the weight is set to Float.MAX_VALUE (worst possible weight).
* dijkstra(sourceVertex, destinationVertex, weightEdgeFieldName, direction)
All edges with "weightEdgeFieldName" are considered in the specified "direction". If "weightEdgeFieldName" is missing or NULL the weight is set to Float.MAX_VALUE (worst possible weight).
* dijkstra(sourceVertex, destinationVertex, weightEdgeFieldName, direction, edgeType)
New version; only edges of the specified "edgeType" in the specified "direction" are considered.

Shall I change the original dijkstra function in my branch and update this pull request?

@w3aponx There could be more than one edgeType in the new version:
* dijkstra(sourceVertex, destinationVertex, weightEdgeFieldName, direction, edgeType [, edgeType-n]*)

**Comment by mbhulin** [comment]
@luigidellaquila In issue #4946 Luca suggested to reimplement the dijkstra function to increase performance. If you do that, you could consider the discussion above. Or shall I try to implement a new version of the dijkstra function based on the actual implementation of shortest path?

**Comment by mbhulin** [comment]
**dijkstra2 function** as extra function additionally to the original dijkstra function **deleted**.
**dijkstra3 function** added instead which could **replace** the original **dijkstra function**.
Differences of dijkstra3 to dijkstra:
* If source and destination coincide return the trivial path with only one vertex instead of an empty path
* If an edge has no 'weight' field or the 'weight' field is null this edge is not considered for routing (gets the maximal possible weight)
* The result is List<ORID> instead of LinkedList<OrientVertex>
* If no path exists the result is an empty list instead of null
* Additional optional fifth parameter:  the edge type i. e. the subclass of E considered for routing; default is E (all edges)
* Implementation uses a priority queue

**Comment by lvca** [comment]
Hi @mbhulin thanks for the contribution. I think dijkstra3 function could replace current dijkstra function. @luigidellaquila WDYT?

**Comment by saeedtabrizi** [comment]
Hi , @mbhulin, @lvca , @luigidellaquila 
Based On http://theory.stanford.edu/~amitp/GameProgramming/Heuristics.html if we return a fixed number in heuristic part of A Star function our result must be equal to Dijkstra’s function . 
I suggest use the a star implementation with zero heuristic value to achieve more functionality in Dijkstra function . 

Thanks 
Saeed Tabrizi

**Comment by luigidellaquila** [comment]
@saeedtabrizi +1, I'm rewriting current Dijkstra implementation to delegate to A* algorithm

**Pull request closed without merging**
