### PR TITLE
wow cache: fix truncate on delete

### PR DESCRIPTION
**Pull request by grossvater**
I would like to have it integrated also on 2.1.x branch.

### CODE REVIEW

**Comment by lvca** [comment]
@laa could you please review it?

**Comment by laa** [comment]
Hi sorry but I do not see a point in truncate in a case of delete.

**Comment by grossvater** [comment]
@laa Please take a look at this issue: https://github.com/orientechnologies/orientdb/issues/5328
and see which is my scenario: when the files are hard linked, deleting them doesn't actually delete the data if there are other links to the file. If we truncate at delete, the other links will point to empty / corrupted files and this is what I try to avoid. I really need this feature, because I do not want to maintain a fork just to have this. Thanks.

**Comment by laa** [comment]
@grossvater I have read the issue. But files do not reflect the real state of the database and update them outside of server control will lead to data corruption.

**Comment by grossvater** [comment]
@laa Regarding the modification outside of the server control, I never do this (I always update the database through local or remote connections), maybe you could rephrase a bit, cause I do no understand what you mean. 
Anyway, all the magic with hard linked files was an workaround to preserve the files after database is dropped. What I actually needed was a way to detach the database (unregister the database and leave the files unchanged), but this feature seems to need more work. So for a while, skipping file truncation will help me a lot, and as far as I remember, all tests passed.

**Comment by laa** [comment]
@grossvater I mean if you access the same files from different JVMs you will have problems with data consistency, because the state of the file on disk does not reflect a current state of a database system.

**Comment by grossvater** [comment]
@laa I do not access the files from different JVM at the same time

**Comment by laa** [comment]
@grossvater OK you persuaded me. I will provide change in next 2.2 snapshot

**Comment by grossvater** [comment]
@laa Great. Thank you!

**Comment by laa** [comment]
@grossvater I just checked , I have already done that in 2.2.x .So you may safely update to 2.2.x and use this feature out of the box.

**Comment by grossvater** [comment]
@laa Super! Thanks!

**Pull request closed without merging**
