### PR TITLE
Add ability to undo one field

### PR DESCRIPTION
**Pull request by PhantomYdn**
Related to issue #3377 

Guys, please consider merging this into 2.0 Final.

### CODE REVIEW

**Comment by lvca** [comment]
@tglman please could you check this PR and in case merge it?

**Comment by tglman** [comment]
Hi @PhantomYdn,

Nice pull request, anyway there are a couple of things to correct,  the first is if no value was changed fieldOriginalValues can be null, the second if you do an undo of a never changed filed it will set it to null, instead of do nothing, you can use containsKey to check that the value was changed.

a couple of tests also in this two cases will be cool ;)

**Comment by PhantomYdn** [comment]
@tglman 
You are right! Btw, your implementation of undo() was valnurable for NPE too.

Guys,

Please-please, include it to 2.0 Final.
It's really important for raleasing Orienteer 1.0... Without per field basis undo: it's not possible to have calculable attributes.

**Comment by lvca** [comment]
Thanks!

**Pull request merged**
