### PR TITLE
Fixes #3982

### LINKED ISSUE #3982: including return { f: $val } in SQL script does not return a record with key / value pairs using binary protocol
When using the binary protocol, the following SQL script:

```
let res = INSERT INTO V SET name = 'bill' RETURN @rid
return { result: $res }
```

The expected result should be a record type with a key of `result` and a value of type `RID`, instead it simply returns a list of RIDs

However, using the HTTP protocol does return the expected result.

### PR DESCRIPTION
**Pull request by stuartcarnie**
Ideally, OCommandExecutorScript would return ODocument, so there
was no special casing required in either ONetworkProtocolBinary of the
HTTP protocol. I am not familiar enough with the reasoning, so I emulated
 the behavior from the HTTP protocol

### CODE REVIEW

**Comment by stuartcarnie** [comment]
This logic was duplicated from the [HTTP protocol implementation](https://github.com/orientechnologies/orientdb/blob/master/server/src/main/java/com/orientechnologies/orient/server/network/protocol/http/OHttpResponse.java#L202-L208)

**Comment by stuartcarnie** [comment]
@lvca this is the pull request :)

**Comment by lvca** [comment]
@stuartcarnie You're right. I opened it from another URL and I cannot see as is. Thanks!

**Comment by lvca** [comment]
Thanks!

**Comment by tglman** [comment]
is missing the test case, would be cool get another pull with a proof of use case.

**Pull request merged**
