### PR TITLE
Schema validation : support for LinkBag (min, max)

### PR DESCRIPTION
**Pull request by voondo**

### CODE REVIEW

**Comment by tglman** [comment]
hi @voondo,

The code look ok, but there is no test case that actually prove that it work, will be cool have some.

**Comment by voondo** [comment]
Ok I'll provide it asap.

**Comment by tglman** [comment]
hi @voondo,

any news on this ?
You may just add the needed check here : https://github.com/orientechnologies/orientdb/blob/develop/core/src/test/java/com/orientechnologies/orient/core/record/impl/ODocumentValidationTest.java#L302

and  here: https://github.com/orientechnologies/orientdb/blob/develop/core/src/test/java/com/orientechnologies/orient/core/record/impl/ODocumentValidationTest.java#L402

Bye

**Comment by voondo** [comment]
Here is a new commit with the tests.
However, they fail with:
```
testMinValidation on testMinValidation(com.orientechnologies.orient.core.record.impl.ODocumentValidationTest)(com.orientechnologies.orient.core.record.impl.ODocumentValidationTest)  Time elapsed: 0.077 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.ORecordNotFoundException: 
The record with id '#40:50' was not found
        DB name="ODocumentValidationTest"
        at com.orientechnologies.orient.core.record.impl.ODocumentValidationTest.checkField(ODocumentValidationTest.java:769)
        at com.orientechnologies.orient.core.record.impl.ODocumentValidationTest.testMinValidation(ODocumentValidationTest.java:483)
Caused by: java.lang.IllegalArgumentException: Cluster segment #40 does not exist in database 'ODocumentValidationTest'
        at com.orientechnologies.orient.core.record.impl.ODocumentValidationTest.checkField(ODocumentValidationTest.java:769)
        at com.orientechnologies.orient.core.record.impl.ODocumentValidationTest.testMinValidation(ODocumentValidationTest.java:483)

testMaxValidation on testMaxValidation(com.orientechnologies.orient.core.record.impl.ODocumentValidationTest)(com.orientechnologies.orient.core.record.impl.ODocumentValidationTest)  Time elapsed: 0.068 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.ORecordNotFoundException: 
The record with id '#40:30' was not found
        DB name="ODocumentValidationTest"
        at com.orientechnologies.orient.core.record.impl.ODocumentValidationTest.checkField(ODocumentValidationTest.java:769)
        at com.orientechnologies.orient.core.record.impl.ODocumentValidationTest.testMaxValidation(ODocumentValidationTest.java:368)
Caused by: java.lang.IllegalArgumentException: Cluster segment #40 does not exist in database 'ODocumentValidationTest'
        at com.orientechnologies.orient.core.record.impl.ODocumentValidationTest.checkField(ODocumentValidationTest.java:769)
        at com.orientechnologies.orient.core.record.impl.ODocumentValidationTest.testMaxValidation(ODocumentValidationTest.java:368)
```
But I don't understand why because I've done like `linklist`... Maybe could it be obvious for you ?

Also I didn't succeeded to run a single test with maven. I tried thins like `mvn -Dtest=ODocumentValidationTest test` but it doesn't work. Any clue ?

**Comment by tglman** [comment]
hi @voondo,

That's error is because some lazy load has been tiggered, i'll double check your code and let you know.

That's why i asked for test  :D

**Comment by voondo** [comment]
Actually it's not very clear to me. I just wanted to add such constraints on _createEdgeProperty_. 
It worked during the 2.2-beta but for an other reason, I no longer use them for now so I cannot tell more...

**Comment by tglman** [comment]
fixed, the cause, merging this on develop.

**Pull request merged**
